### PR TITLE
Users table seeder

### PR DESCRIPTION
**Pull request by James-N-M**
I wrote this quick seeder to get myself going, got the users table populated with the 51 users. But was unable to login due to 

ERROR for site owner:
Invalid domain for site key 

Not entirely sure what this means let me know !

### CODE REVIEW

**Comment by James-N-M** [comment]
@ig-89 Once I figure out this environment set up properly, maybe I can write some documentation for you as well for other people who'd like to contribute.

**Comment by isg89** [comment]
@James-N-M Hmmm, I'll look into the "Invalid domain for site key" error. Documentation would be great! I also probably need to go back and refactor some of the code on the backend (such as the Game model and Controller) and the front end as well.

**Comment by James-N-M** [comment]
@ig-89 not sure maybe something was blocked at my work, logged in just fine this morning. Updated the seeder should be fine now. let me know if this is ok for you just for the users stuff at least. I'm going to create each in a separate branch.... and the corresponding controller tests.. itll help me learn the code and the project get at least some testing haha.

**Comment by James-N-M** [comment]
I think it has something to do with the recapcha thingyyy in the Register.vue component sitekey: '6LcQXk8UAAAAAIaCSzs026CYI7F7sP5PFd8pNNj7' Im not entirely sure what this means or how to get a different one that might work 🦆

**Comment by isg89** [comment]
That sitekey is required for Google's ReCAPTCHA. Mythril currently uses this Vue Component ([vue-recaptcha](https://github.com/DanSnow/vue-recaptcha)). 

Ahh the error "Invalid domain for site key" is starting to make sense, Google's ReCAPTCHA, is probably expecting a request from mythril.io (if i understand it correctly). I'll take a deeper look, this might be the solution - [how-to-test-vue-recaptcha](https://github.com/DanSnow/vue-recaptcha#how-to-test-vue-recaptcha).

Side Note: I just noticed Google Introduced version 3 of their ReCAPTCHA, might implement that later on.

**Comment by James-N-M** [comment]
@ig-89 Whats your dev environment set up to make this work though ? my mac uses laravel valet and my work computer uses a vagrant homestead box.

**Comment by isg89** [comment]
On my Mac, I use laravel valet and on my windows machine, I use laragon. Is the only issue you're having the sitekey error?

**Comment by James-N-M** [comment]
I've never used laragon before sounds pretty cool, and yes ERROR for site owner:
Invalid domain for site key , it basically makes the register and login vue components not work, its definitely the vue-recapcha thing and the site-key data property is hardcoded so I'm assuming it needs to be specific per environment maybe. maybe we can have a google hangout call or something I'm in Eastern Daylight Time
Time zone in Windsor, ON (GMT-4)
Saturday, April 27, 2019, 3:20 p.m.

**Comment by isg89** [comment]
Yeah we could do that. I'm going to pull the github repo and setup a new local environment again to see if I get that site key issue. Also I don't believe the site key value is different per environment. I'll try it and report back. 

What are the steps you are taking when pulling in the git repo? 
ex.
1. npm install 
2. npm run watch

**Comment by James-N-M** [comment]
I forked it (might be an issue),
1. composer install 
2. php artisan key:generate 
3. .env.eample to .env changes, create a database locally map all that up, basically the basic .env set up
4. npm install
5. npm run dev or watch both work 
- doing this adds the modifications to the public folder which will probs turn into a hassle if someone or me ever makes vue component changes, should probablly add this stuff to the .gitignore

**Comment by isg89** [comment]
I made a fork of the master branch and I'm running into the same issue. I also just checked my local environment and I have the same issue for registering new users (I guess it never was a concern for me, since I didn't have a need to create a new user). 

I found the solution though, on Google's ReCaptcha website: [I'm getting an error "Localhost is not in the list of supported domains". What should I do?](https://developers.google.com/recaptcha/docs/faq#localhost_support)

For the time being I've added localhost to the list of supported domains, I might create a separate key in the future for development environments. I believe when I was setting up ReCaptcha, I didn't include localhost as a domain due to Google's suggestion on keeping it separate. I think I never bothered to create a separate one for development though lol

I'll also update the .gitignore for the public folder and there is a development branch, it's called dev, it's probably best to use that one instead of master.

**Comment by James-N-M** [comment]
Awesome I’ll give the setup a go again

**Comment by James-N-M** [comment]
let me know what your .env looks like to get a login working i think mine must be missing something registration page still showing the invalid ERROR for site owner:
Invalid domain for site key message message. 
``` 
APP_NAME=mythril
APP_ENV=local
APP_KEY=base64:Ue4l+UPKukLxFH054ddLM2J9U0Vd9D3OMh6QNJ9UzcM=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://mythril.test

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=mythril
DB_USERNAME=root
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
```

**Comment by isg89** [comment]
Ahh I think it might be because you're accessing the local website via "mythril.test". Is there anyway using valet, you can change the domain to localhost? If not, I can add "mythril.test" to the domain list.

**Comment by James-N-M** [comment]
@ig-89 I'm not sure if this will mess up my other projects I'm using valet for, if its tough / a security issue for you to add mythril.test ill figure it out. if not that'd be great if you could add it

**Comment by isg89** [comment]
@James-N-M I've added mythril.test for the time being. In the future might change that.

**Comment by James-N-M** [comment]
still having issues logging in sadly :( recapcha doesn't validate, creating a user manually and logging in also doesn't seem to want to work, and when i try to go away from register page then back it doesn't load up and just hangs with the very nice looking scroll wheel haha. Let me know if you wanna have a call this threads getting a bit long lol.

**Comment by isg89** [comment]
hmm that's odd, I'm having the same issue, let me investigate this a little further but after I complete the forums (I haven't been able to give it much attention and I don't want the task to drag on for too long lol).

**Pull request closed without merging**
